version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: roomease-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: roomease
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: roomease-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@roomease.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres-data:
