version: '3.8'
services:
  mysql:
    image: mysql:8.4
    container_name: room_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: room_db
      MYSQL_USER: room_user
      MYSQL_PASSWORD: room_pass
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
